app:
  mongodb:
    uri: 

spring:
  security: 
    oauth2: 
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7001/auth/.well-known/jwks.json

  jackson:
    default-property-inclusion: NON_ABSENT
  
  batch: 
    initialize-schema: NEVER
    job:
      enabled: false
      

logging:
  level:
    org.springframework: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.security: WARN
    com.box.sdk: DEBUG
    com.cheetahapps.sales: INFO
    