app:
  mongodb:
    uri: mongodb+srv://umpun20:xqzeUgbrLiCd2aC3@cluster0-wsps7.mongodb.net/coredb?retryWrites=true&w=majority
  aws:
    s3:
      accessKeyId: AKIAX226J2W5KBUW4T5D
      accessKeySecret: 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
  authz:
    jwt:
      issuer: http://localhost:7001/auth/issuer
  document:
    storage:
      provider: s3
  
spring:
  jackson:
    default-property-inclusion: NON_ABSENT
  
  batch: 
    initialize-schema: NEVER
    job:
      enabled: false
      
  
smtp:
  user: support@cheetahdesk.com
  password: "@Kolkata84"
  server: smtp.dreamhost.com
  port: 465
  useTls: true

logging:
  level:
    org.springframework: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO
    com.cheetahapps.sales: INFO
    org.springframework.web.client: INFO
    
