app:
  mongodb:
    uri: mongodb+srv://JayCluster:j_02221459@cluster0-fsas8.mongodb.net/test?retryWrites=true&w=majority
  aws:
    s3:
      accessKeyId: AKIAX226J2W5KBUW4T5D
      accessKeySecret: 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
  authz:
    jwt:
      issuer: http://localhost:7001/auth/issuer
  document:
    storage:
      provider: s3
  
spring:
  jackson:
    default-property-inclusion: NON_ABSENT
  
  batch: 
    initialize-schema: NEVER
    job:
      enabled: false
      
  
smtp:
  user: support@cheetahdesk.com
  password: '@Kolkata84'
  server: smtp.dreamhost.com
  port: 587
  useTls: true

logging:
  level:
    org.springframework: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: INFO
    com.cheetahapps.sales: INFO
    org.springframework.web.client: INFO
    javax.mail: DEBUG
    jodd.mail: DEBUG
    
