app:
  mongodb:
    uri: 
  default:
    currency: USD
spring:
  jackson:
    default-property-inclusion: NON_ABSENT
  
  batch: 
    initialize-schema: NEVER
    job:
      enabled: false
      

    